// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7ieelYUjDrmWPRoLpEsWCzq5K8833L84',
    appId: '1:507671487778:web:9d47264559c036cc34717b',
    messagingSenderId: '507671487778',
    projectId: 'chatapp-beeda',
    authDomain: 'chatapp-beeda.firebaseapp.com',
    storageBucket: 'chatapp-beeda.appspot.com',
    measurementId: 'G-SJPYWDLGM3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqByeA_QRYS0AvkXEMNepSvjaYyL-qSHs',
    appId: '1:507671487778:android:4db668d2d7231f8b34717b',
    messagingSenderId: '507671487778',
    projectId: 'chatapp-beeda',
    storageBucket: 'chatapp-beeda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxkHVezcfwj853oAHGAngANy9iJKcmJ1E',
    appId: '1:507671487778:ios:aba6ad9ba2bddab334717b',
    messagingSenderId: '507671487778',
    projectId: 'chatapp-beeda',
    storageBucket: 'chatapp-beeda.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxkHVezcfwj853oAHGAngANy9iJKcmJ1E',
    appId: '1:507671487778:ios:4b8e80817d98485c34717b',
    messagingSenderId: '507671487778',
    projectId: 'chatapp-beeda',
    storageBucket: 'chatapp-beeda.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
